# Controlly Example Dashboard Configuration

pages:
  home:
    title: Dashboard
    icon: home
    widgets:
      - type: sensor
        entity_id: sensor.living_room_multisensor_temperature
      - type: sensor
        entity_id: sensor.master_bedroom_multisensor_temperature
      - type: sensor
        entity_id: sensor.nursery_multisensor_temperature
      - type: sensor
        entity_id: sensor.garage_multisensor_temperature

  lights:
    title: Lighting
    icon: lamp

  climate:
    title: Climate
    icon: thermometer
    widgets:
      - type: sensor
        entity_id: sensor.living_room_multisensor_relative_humidity
      - type: sensor
        entity_id: sensor.master_bedroom_multisensor_relative_humidity
      - type: sensor
        entity_id: sensor.nursery_multisensor_relative_humidity

  security:
    title: Security
    icon: lock

  maintenance:
    title: Maintenance
    icon: wrench